#!/bin/sh

# add ~/.bin to path
if [ -n "${PATH##*:$HOME/.bin*}" ] && [ -d "$HOME/.bin" ]; then
    export PATH=$HOME/.bin:$PATH
fi

# add ~/.local/bin to path
if [ -n "${PATH##*:$HOME/.local/bin*}" ] && [ -d "$HOME/.local/bin" ]; then
    export PATH=$HOME/.local/bin:$PATH
fi

# add go to path
if [ -n "${PATH##*:/usr/local/go/bin*}" ] && [ -d /usr/local/go ]; then
    export PATH=$PATH:/usr/local/go/bin
fi

# add pypi to path
if [ -d "$HOME/Library/Python" ]; then
    PYPI_PATH="$(ls -1d $HOME/Library/Python/*/bin 2>/dev/null | head -n1)"
    [ -n "$PYPI_PATH" ] && export PATH="$PATH:$PYPI_PATH"
    unset PYPI_PATH
fi

# set TERM variable
if [ "$TERM" = "xterm" ]; then
    export COLORTERM="xterm-256color"
    export TERM="xterm-256color"
fi

# latex environment variables
if [ -e "$HOME/.latex" ]; then
    export TEXINPUTS=.:$HOME/.latex:
    export BSTINPUTS=$TEXINPUTS
    export BIBINPUTS=$TEXINPUTS
fi

# python startup
if [ -e "$HOME/.pythonrc" ]; then
    export PYTHONSTARTUP="$HOME/.pythonrc"
fi

# make less more friendly for non-text input files, see lesspipe(1)
if [ -x /usr/bin/lesspipe  ]; then
    eval "$(SHELL=/bin/sh lesspipe)"
fi

# load color palette for dir listing
if [ -f "$HOME/.dircolors" ] && hash dircolors 2>/dev/null; then
    eval $(dircolors -b $HOME/.dircolors)
fi

# set bc options
if [ -f "$HOME/.bc" ]; then
    export BC_ENV_ARGS="$HOME/.bc"
fi

# set vim as default editor
if hash nvim 2>/dev/null; then
    export EDITOR="nvim"
elif hash mvim 2>/dev/null; then
    export EDITOR="mvim -v"
elif hash vim 2>/dev/null; then
    export EDITOR="vim"
fi
export VISUAL=$EDITOR

# set less as default pager
if hash lesscolor 2>/dev/null; then
    export MANPAGER="lesscolor"
elif hash less 2>/dev/null; then
    export MANPAGER="less"
fi

# set chrome as default browser
if hash google-chrome 2>/dev/null; then
    export BROWSER='google-chrome'
elif hash croshclip 2>/dev/null; then
    export BROWSER='croshclip -url'
fi

# color in terminal
export CLICOLOR="Yes"

# color in ack
export ACK_MATCH_COLOR="bold red"

# color in ls
export LS_OPTIONS="--color=auto"
# for Darwin
if [ -z "${OSTYPE##*darwin*}" ]; then
    LS_OPTIONS="-G"
fi

# color man pages
export LESS="-RSc"

# set up options for fzf
export FZF_DEFAULT_OPTS='--bind alt-p:page-up,alt-n:page-down'
export FZF_CTRL_R_OPTS='-e'
if [ "$(type -t fd)" = "file" ]; then
  export FZF_DEFAULT_COMMAND='fd'
  export FZF_CTRL_T_COMMAND='fd'
  _fzf_compgen_path() {
        fd --hidden --follow --exclude ".git" . "$1"
  }
  _fzf_compgen_dir() {
        fd --type d --hidden --follow --exclude ".git" . "$1"
  }
elif [ "$(type -t rg)" = "file" ]; then
  export FZF_DEFAULT_COMMAND='rg --files'
  export FZF_CTRL_T_COMMAND='rg --files'
elif [ "$(type -t ag)" = "file" ]; then
  export FZF_DEFAULT_COMMAND='ag -l'
  export FZF_CTRL_T_COMMAND='ag -l -g ""'
fi
